-- MySQL Script generated by MySQL Workbench
-- dom 22 nov 2020 20:15:19 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_nacimiento` VARCHAR(45) NOT NULL,
  `DNI_cabeza` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `DNI_idx` (`DNI_cabeza` ASC),
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI_cabeza`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Cocejal` VARCHAR(45) NOT NULL,
  `Ubicacion` VARCHAR(45) NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Habitantes` INT GENERATED ALWAYS AS (),
  `Nombre_zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Calle`, `Numero`),
  INDEX `Nombre_zona_idx` (`Nombre_zona` ASC),
  CONSTRAINT `Nombre_zona`
    FOREIGN KEY (`Nombre_zona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Planta` INT NOT NULL,
  `Letra` VARCHAR(1) NOT NULL,
  `Portal` VARCHAR(45) NOT NULL,
  `Habitantes` INT GENERATED ALWAYS AS (),
  `Tamaño` INT NOT NULL,
  `DNI_dueño` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Calle`, `Planta`, `Letra`, `Portal`, `Numero`),
  INDEX `DNI_dueño_idx` (`DNI_dueño` ASC),
  INDEX `Bloque_idx` (`Calle` ASC, `Numero` ASC),
  CONSTRAINT `Bloque`
    FOREIGN KEY (`Calle` , `Numero`)
    REFERENCES `mydb`.`Bloque` (`Calle` , `Numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DNI_dueño`
    FOREIGN KEY (`DNI_dueño`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivienda` (
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Habitantes` INT GENERATED ALWAYS AS (),
  `Tamaño` INT NOT NULL,
  `Nombre_zona` VARCHAR(45) NOT NULL,
  `DNI_dueño` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Calle`, `Numero`),
  INDEX `Zona_idx` (`Nombre_zona` ASC),
  INDEX `Persona_idx` (`DNI_dueño` ASC),
  CONSTRAINT `Zona`
    FOREIGN KEY (`Nombre_zona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `Persona`
    FOREIGN KEY (`DNI_dueño`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivienda_Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivienda_Unifamiliar` (
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Calle`, `Numero`, `DNI`),
  INDEX `Persona_idx` (`DNI` ASC),
  CONSTRAINT `Vivienda`
    FOREIGN KEY (`Calle` , `Numero`)
    REFERENCES `mydb`.`Vivienda` (`Calle` , `Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Persona`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso_Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso_Persona` (
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Planta` INT NOT NULL,
  `Letra` VARCHAR(1) NOT NULL,
  `Portal` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`Calle`, `Numero`, `Planta`, `Letra`, `Portal`, `DNI`),
  INDEX `Persona_idx` (`DNI` ASC),
  CONSTRAINT `Piso`
    FOREIGN KEY (`Calle` , `Numero` , `Planta` , `Letra` , `Portal`)
    REFERENCES `mydb`.`Piso` (`Calle` , `Numero` , `Planta` , `Letra` , `Portal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Persona`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`Persona` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Catastro`.`Vivienda_Unifamiliar_BEFORE_INSERT` BEFORE INSERT ON `Vivienda_Unifamiliar` FOR EACH ROW
BEGIN
SET @vive = (SELECT COUNT(Portal) FROM Piso_Persona WHERE DNI = NEW.DNI);
SET @vive1 = (SELECT COUNT(Numero) FROM Vivienda_Unifamiliar WHERE DNI = NEW.DNI);
IF (@vive > 0 OR @vive1 > 0) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Esta persona no puede vivir en dos viviendas a la vez';
END IF;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Catastro`.`Piso_Persona_BEFORE_INSERT` BEFORE INSERT ON `Piso_Persona` FOR EACH ROW
BEGIN
SET @vive = (SELECT COUNT(Portal) FROM Piso_Persona WHERE DNI = NEW.DNI);
SET @vive1 = (SELECT COUNT(Numero) FROM Vivienda_Unifamiliar WHERE DNI = NEW.DNI);
IF (@vive > 0 OR @vive1 > 0) THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Esta persona no puede vivir en dos vivienda a la vez';
END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
